baseURL = "http://blog.stefan.org/"
title = "🙈   🙉"

publishDir = "docs"
languageCode = "en-us"
author = "coldsauce"

[params]
  logo      = "/images/stylish.jpg"
  twitter   = "https://twitter.com/stayfun_"
  github    = "https://github.com/coldsauce/"
  email     = "stefan@stefanaleksic.com"

