baseURL = "https://blog.stefanaleksic.com"
title = "🙈   🙉"

publishDir = "docs"
languageCode = "en-us"
author = "coldsauce"
theme = "hugo-zen"
googleAnalytics = "UA-136703198-1"

[params]
  logo      = "images/stylish.jpg"
  twitter   = "https://twitter.com/stayfun_"
  github    = "https://github.com/coldsauce/"
  email     = "stefan@stefanaleksic.com"

