baseURL = "https://coldsauce.github.io/"
title = "🙈   🙉"

publishDir = "docs"
languageCode = "en-us"
author = "coldsauce"
theme = "hugo-zen"

[params]
  logo      = "/docs/images/stylish.jpg"
  twitter   = "https://twitter.com/stayfun_"
  github    = "https://github.com/coldsauce/"
  email     = "stefan@stefanaleksic.com"

